#!/usr/bin/env bash

# Global go install script

# For all platform, please refer to https://golang.org/doc/install/source

# set -x

CurrentDir="$(pwd)"
# TAKOV2="${CurrentDir/\/src\/github.com\/xgsdk2\/betatest\/gotako/}"
# export GOPATH=$TAKOV2:$CurrentDir
export GOPATH=$CurrentDir
export GOOS=linux
export GOARCH=amd64
go install -ldflags "-s -w" takows
# go install -ldflags "-s -w" takofs
# go install -ldflags "-s -w" takoup

#export GOOS=linux
#export GOARCH=arm
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
#go install -ldflags "-s -w" takoup

#export GOOS=linux
#export GOARCH=386
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
#go install -ldflags "-s -w" takoup

# export GOOS=darwin
# export GOARCH=amd64
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
# go install -ldflags "-s -w" takoup

#export GOOS=darwin
#export GOARCH=386
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
#go install -ldflags "-s -w" takoup

# export GOOS=windows
# export GOARCH=amd64
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
# go install -ldflags "-s -w" takoup

#export GOOS=windows
#export GOARCH=386
#go install -ldflags "-s -w" github.com/yaosxi/mgox
#go install -ldflags "-s -w" takows
#go install -ldflags "-s -w" takofs
#go install -ldflags "-s -w" takoup