# 请修改 project_file_path 为工程在本机的实际路径
project_file_path: /Users/xionghaitao/01_to_games/jxqy_8c/jx8c/Unity-iPhone.xcodeproj

# 请修改工程的 targetName
targetName: ios-bi-demo

# 以下参数无需修改
XgAuthUrl: http://onsite.auth.xgsdk.com:8180
XgDataUrl: http://data.xgsdk.com
appKey: sGxvORLhZo6OTFbd
appId: 10016
xgsdk_channelid: ios_jinshanApple
bundle_id: com.game.jianxia1
xgsdkBuildNumber: 1.0.0
xgsdkPlanId: 294
xgsdkServerVersion: v1
xgsdk_sdkAppid: 2098
xgsdk_sdkAppkey: 3b2c9da55872423bbc33102c8e8df84b
XgRechargeUrl: http://p2.xgsdk.com
isUsePure: false
