#!/usr/bin/env bash

# Global go install script

# For all platform, please refer to https://golang.org/doc/install/source

# set -x

pid=`pgrep myPackage`
# echo $pid
if [ $pid ]; then
kill -9 $pid
fi

cd bin
./myPackage